### ISSUE TITLE
Case files

### ISSUE THREAD

**Issue by lubbertkramer** [paviro/HASS-YAAP#2]
Did you print the case yourself or did you also buy this? If you have printed it where can i find the files ?

Thanks!

**Comment by paviro** [comment]
The case was designed by a friend of mine. He is still finishing up some things as soon as he is done I’ll add it to the repo.

**Comment by lubbertkramer** [comment]
Great to hear! But is it possible to also share the case you have used/printed?

**Comment by paviro** [comment]
Mhh? As I said it’s still being finished up. I had to improvise some things on the particular one I printed.

**Comment by paviro** [comment]
Files added at https://github.com/paviro/HASS-YAAP/tree/main/stl
