### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by r0667002** [paviro/HASS-YAAP#3]
Hi! I'm planning to make this myself, but was wondering which exact libraries you are using in PlatformIO?

**Comment by paviro** [comment]
See `lib_deps` in https://github.com/paviro/HASS-YAAP/blob/main/platformio.ini :)

**Comment by r0667002** [comment]
Ahh how silly of me! Clearly still new to all of this ;) Thanks a lot for the project (and your help ofc)!

**Comment by paviro** [comment]
No worries! Good look on your building journey and have fun!
