### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by iObi** [paviro/HASS-YAAP#4]
I am totally new to PlatformIO and I have read the manual but I am struggling with the libaries.
I have added to following to platformio.ini

lib_deps = 
	plapointe6/EspMQTTClient@^1.11.1
	arkhipenko/Dictionary@^3.2.1
	chris--a/Keypad@^3.1.1
	marcoschwartz/LiquidCrystal_I2C@^1.1.4

But I get the following errors when building:

*** [.pio\build\nodemcu\lib32b\LiquidCrystal_I2C\LiquidCrystal_I2C.cpp.o] Error 1
Compiling .pio\build\nodemcu\FrameworkArduino\Stream.cpp.o
*** [.pio\build\nodemcu\lib30f\EspMQTTClient\EspMQTTClient.cpp.o] Error 1

Just adding
lib_deps = 
	plapointe6/EspMQTTClient@^1.11.1
	arkhipenko/Dictionary@^3.2.1
	chris--a/Keypad@^3.1.1
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
to the ini file is that enough or do I need to download these libaries myself?

**Comment by paviro** [comment]
Why not just open the existing project instead of adding it to a new platformio.ini?

Not sure to be honest first time I used it myself for this. I guess if you open the folder/project after pulling it from git it should download them automatically but not sure to be honest.

**Comment by iObi** [comment]
Thanks for your help, opening the existing project solved my issues.
