### ISSUE TITLE
automation issue

### ISSUE THREAD

**Issue by dasc19** [paviro/HASS-YAAP#5]
Hi! I'm trying to make this myself,but I'm facing a issue with the automation  to change the state of the alarm system-    I check it on the the template editor of HA and I have the message   " UndefinedError: 'trigger' is undefined".

Any idea what can be the cause ?

Thanks for your support

**Comment by paviro** [comment]
Not sure what you mean. What exactly did you check in the template editor?

**Comment by dasc19** [comment]
I checked the YAML file for the automation

**Comment by paviro** [comment]
Why though? The template editor is there to write and check templates not automations. See [here](https://community.home-assistant.io/t/how-do-i-mix-manual-automations-in-yaml-files-with-use-of-blueprints/295730/2) on how to add manual automations to the configuration file.

**Comment by dasc19** [comment]
Ok, Thanks a lot

**Comment by paviro** [comment]
Good luck!

**Comment by dasc19** [comment]
Hi there,sorry to disturb you again .Now I'm stuck because I receive the message on the LCD "  Alarm System Inactive    ".When I take a look to MQTT explorer when the alarm changes states the messages are correct. I also noticed that it takes a a while to connect to the server.  maybe my MQTT credentials are NOK??'
Your support is more than welcome
PS: I just connect the LCD and the ESP8266
